image: atlassian/default-image:latest
clone:
  depth: full
pipelines:
  default:
      - step:
          script:
            - cat ./deploy.sh | ssh root@134.209.222.226
            - echo "Deploy step finished"
  branches:
    develop:
      - step:
          deployment: staging
          script:
            - cat ./deploy.sh | ssh root@134.209.222.226
            - echo "Deploy step finished"
    master:
      - step:
          deployment: live
          script:
            - cat ./configs/deploy.sh | ssh root@134.209.222.226
            - echo "Deploy step finished"