image: python:3.7.3

clone:
  depth: full
pipelines:
  default:
      - step:
          script:
            - cat ./configs/deploy.sh | ssh root@134.209.222.226
            - echo "Deploy step finished"
  branches:
    develop:
      - step:
          deployment: staging
          script:
            - cat ./configs/deploy.sh | ssh root@134.209.222.226
            - echo "Deploy step finished"
    master:
      - step:
          deployment: production
          script:
            - cat ./configs/deploy.sh | ssh root@134.209.222.226
            - echo "Deploy step finished"
